/** Declaration file generated by dts-gen */

export = express_flash;

declare function express_flash(...args: any[]): any;

declare namespace express_flash {
    const prototype: {
    };

    const version: string;

}

